// Code generated by zapredactor. DO NOT EDIT.
package main

import (
	"github.com/jamillosantos/zapredactor"
	"go.uber.org/zap/zapcore"
)

func (s Expiry) Redact(encoder zapcore.ObjectEncoder) error {
	encoder.AddString("Month", zapredactor.RedactValue(s.Month, ""))
	encoder.AddInt("Year", s.Year)
	return nil
}

func (s CreditCard) Redact(encoder zapcore.ObjectEncoder) error {
	encoder.AddString("pan", zapredactor.RedactValue(s.PAN, ""))
	encoder.AddString("card_holder", zapredactor.RedactValue(s.CardHolder, ""))
	encoder.AddString("CVV", zapredactor.RedactValue(s.CVV, ""))
	encoder.AddObject("Expiry", zapredactor.RedactObject(&s.Expiry))
	encoder.AddString("First4", s.First4)
	encoder.AddString("Last4", s.Last4)
	return nil
}

func (s Address) Redact(encoder zapcore.ObjectEncoder) error {
	encoder.AddString("Street", zapredactor.RedactValue(s.Street, ""))
	encoder.AddString("City", zapredactor.RedactValue(s.City, ""))
	return nil
}

func (s Customer) Redact(encoder zapcore.ObjectEncoder) error {
	encoder.AddString("Name", zapredactor.RedactValue(s.Name, ""))
	if s.Card == nil {
		encoder.AddReflected("Card", nil)
	} else {
		encoder.AddObject("Card", zapredactor.RedactObject(s.Card))
	}
	encoder.AddObject("Address", zapredactor.RedactObject(&s.Address))
	return nil
}
