// Code generated by qtc from "object_mashaller.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line object_mashaller.qtpl:1
package templates

//line object_mashaller.qtpl:1
import "github.com/jamillosantos/zapredactor/internal/domain"

//line object_mashaller.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line object_mashaller.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line object_mashaller.qtpl:3
func StreamRedactor(qw422016 *qt422016.Writer, info domain.Package) {
//line object_mashaller.qtpl:3
	qw422016.N().S(`// Code generated by zapredactor. DO NOT EDIT.
package `)
//line object_mashaller.qtpl:5
	qw422016.E().S(info.Name)
//line object_mashaller.qtpl:5
	qw422016.N().S(`

import (
	"github.com/jamillosantos/zapredactor"
`)
//line object_mashaller.qtpl:9
	if info.IncludeZapArray {
//line object_mashaller.qtpl:9
		qw422016.N().S(`"github.com/jamillosantos/zapredactor/zaparray"`)
//line object_mashaller.qtpl:9
	}
//line object_mashaller.qtpl:9
	qw422016.N().S(`	"go.uber.org/zap/zapcore"
)

`)
//line object_mashaller.qtpl:13
	for _, s := range info.Structs {
//line object_mashaller.qtpl:14
		StreamRenderStruct(qw422016, s)
//line object_mashaller.qtpl:14
		qw422016.N().S(`
`)
//line object_mashaller.qtpl:15
	}
//line object_mashaller.qtpl:15
	qw422016.N().S(`
`)
//line object_mashaller.qtpl:16
}

//line object_mashaller.qtpl:16
func WriteRedactor(qq422016 qtio422016.Writer, info domain.Package) {
//line object_mashaller.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
//line object_mashaller.qtpl:16
	StreamRedactor(qw422016, info)
//line object_mashaller.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line object_mashaller.qtpl:16
}

//line object_mashaller.qtpl:16
func Redactor(info domain.Package) string {
//line object_mashaller.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
//line object_mashaller.qtpl:16
	WriteRedactor(qb422016, info)
//line object_mashaller.qtpl:16
	qs422016 := string(qb422016.B)
//line object_mashaller.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
//line object_mashaller.qtpl:16
	return qs422016
//line object_mashaller.qtpl:16
}

//line object_mashaller.qtpl:18
func StreamRenderStruct(qw422016 *qt422016.Writer, s domain.RedactedStruct) {
//line object_mashaller.qtpl:18
	qw422016.N().S(`func (s `)
//line object_mashaller.qtpl:19
	qw422016.E().S(s.Name)
//line object_mashaller.qtpl:19
	qw422016.N().S(`) Redact(encoder zapcore.ObjectEncoder) error {
`)
//line object_mashaller.qtpl:20
	for _, field := range s.Fields {
//line object_mashaller.qtpl:20
		qw422016.N().S(`	`)
//line object_mashaller.qtpl:21
		StreamRenderField(qw422016, field)
//line object_mashaller.qtpl:22
	}
//line object_mashaller.qtpl:22
	qw422016.N().S(`	return nil
}

`)
//line object_mashaller.qtpl:26
}

//line object_mashaller.qtpl:26
func WriteRenderStruct(qq422016 qtio422016.Writer, s domain.RedactedStruct) {
//line object_mashaller.qtpl:26
	qw422016 := qt422016.AcquireWriter(qq422016)
//line object_mashaller.qtpl:26
	StreamRenderStruct(qw422016, s)
//line object_mashaller.qtpl:26
	qt422016.ReleaseWriter(qw422016)
//line object_mashaller.qtpl:26
}

//line object_mashaller.qtpl:26
func RenderStruct(s domain.RedactedStruct) string {
//line object_mashaller.qtpl:26
	qb422016 := qt422016.AcquireByteBuffer()
//line object_mashaller.qtpl:26
	WriteRenderStruct(qb422016, s)
//line object_mashaller.qtpl:26
	qs422016 := string(qb422016.B)
//line object_mashaller.qtpl:26
	qt422016.ReleaseByteBuffer(qb422016)
//line object_mashaller.qtpl:26
	return qs422016
//line object_mashaller.qtpl:26
}

//line object_mashaller.qtpl:28
func StreamRenderValueType(qw422016 *qt422016.Writer, field domain.RedactedField, t string) {
//line object_mashaller.qtpl:29
	if field.IsPointer {
//line object_mashaller.qtpl:29
		qw422016.N().S(`	if s.`)
//line object_mashaller.qtpl:30
		qw422016.E().S(field.Name)
//line object_mashaller.qtpl:30
		qw422016.N().S(` == nil {
		encoder.AddReflected("`)
//line object_mashaller.qtpl:31
		qw422016.E().S(field.Name)
//line object_mashaller.qtpl:31
		qw422016.N().S(`", nil)
	} else {
`)
//line object_mashaller.qtpl:33
	}
//line object_mashaller.qtpl:33
	qw422016.N().S(`encoder.Add`)
//line object_mashaller.qtpl:34
	qw422016.E().S(t)
//line object_mashaller.qtpl:34
	qw422016.N().S(`("`)
//line object_mashaller.qtpl:34
	qw422016.E().S(field.ExportedName)
//line object_mashaller.qtpl:34
	qw422016.N().S(`",`)
//line object_mashaller.qtpl:34
	if field.IsPointer {
//line object_mashaller.qtpl:34
		qw422016.N().S(`*`)
//line object_mashaller.qtpl:34
	}
//line object_mashaller.qtpl:34
	qw422016.N().S(`s.`)
//line object_mashaller.qtpl:34
	qw422016.E().S(field.Name)
//line object_mashaller.qtpl:34
	qw422016.N().S(`)
`)
//line object_mashaller.qtpl:35
	if field.IsPointer {
//line object_mashaller.qtpl:35
		qw422016.N().S(`	}
`)
//line object_mashaller.qtpl:37
	}
//line object_mashaller.qtpl:38
}

//line object_mashaller.qtpl:38
func WriteRenderValueType(qq422016 qtio422016.Writer, field domain.RedactedField, t string) {
//line object_mashaller.qtpl:38
	qw422016 := qt422016.AcquireWriter(qq422016)
//line object_mashaller.qtpl:38
	StreamRenderValueType(qw422016, field, t)
//line object_mashaller.qtpl:38
	qt422016.ReleaseWriter(qw422016)
//line object_mashaller.qtpl:38
}

//line object_mashaller.qtpl:38
func RenderValueType(field domain.RedactedField, t string) string {
//line object_mashaller.qtpl:38
	qb422016 := qt422016.AcquireByteBuffer()
//line object_mashaller.qtpl:38
	WriteRenderValueType(qb422016, field, t)
//line object_mashaller.qtpl:38
	qs422016 := string(qb422016.B)
//line object_mashaller.qtpl:38
	qt422016.ReleaseByteBuffer(qb422016)
//line object_mashaller.qtpl:38
	return qs422016
//line object_mashaller.qtpl:38
}

//line object_mashaller.qtpl:40
func StreamRenderArray(qw422016 *qt422016.Writer, field domain.RedactedField, t string) {
//line object_mashaller.qtpl:40
	qw422016.N().S(`encoder.AddArray("`)
//line object_mashaller.qtpl:41
	qw422016.E().S(field.ExportedName)
//line object_mashaller.qtpl:41
	qw422016.N().S(`", zaparray.`)
//line object_mashaller.qtpl:41
	qw422016.E().S(t)
//line object_mashaller.qtpl:41
	qw422016.N().S(`(s.`)
//line object_mashaller.qtpl:41
	qw422016.E().S(field.Name)
//line object_mashaller.qtpl:41
	qw422016.N().S(`))
`)
//line object_mashaller.qtpl:42
}

//line object_mashaller.qtpl:42
func WriteRenderArray(qq422016 qtio422016.Writer, field domain.RedactedField, t string) {
//line object_mashaller.qtpl:42
	qw422016 := qt422016.AcquireWriter(qq422016)
//line object_mashaller.qtpl:42
	StreamRenderArray(qw422016, field, t)
//line object_mashaller.qtpl:42
	qt422016.ReleaseWriter(qw422016)
//line object_mashaller.qtpl:42
}

//line object_mashaller.qtpl:42
func RenderArray(field domain.RedactedField, t string) string {
//line object_mashaller.qtpl:42
	qb422016 := qt422016.AcquireByteBuffer()
//line object_mashaller.qtpl:42
	WriteRenderArray(qb422016, field, t)
//line object_mashaller.qtpl:42
	qs422016 := string(qb422016.B)
//line object_mashaller.qtpl:42
	qt422016.ReleaseByteBuffer(qb422016)
//line object_mashaller.qtpl:42
	return qs422016
//line object_mashaller.qtpl:42
}

//line object_mashaller.qtpl:44
func StreamRenderValueRedacted(qw422016 *qt422016.Writer, field domain.RedactedField, redactor string) {
//line object_mashaller.qtpl:44
	qw422016.N().S(`encoder.AddString("`)
//line object_mashaller.qtpl:45
	qw422016.E().S(field.ExportedName)
//line object_mashaller.qtpl:45
	qw422016.N().S(`", zapredactor.RedactValue(s.`)
//line object_mashaller.qtpl:45
	qw422016.E().S(field.Name)
//line object_mashaller.qtpl:45
	qw422016.N().S(`, "`)
//line object_mashaller.qtpl:45
	qw422016.E().J(redactor)
//line object_mashaller.qtpl:45
	qw422016.N().S(`"))
`)
//line object_mashaller.qtpl:46
}

//line object_mashaller.qtpl:46
func WriteRenderValueRedacted(qq422016 qtio422016.Writer, field domain.RedactedField, redactor string) {
//line object_mashaller.qtpl:46
	qw422016 := qt422016.AcquireWriter(qq422016)
//line object_mashaller.qtpl:46
	StreamRenderValueRedacted(qw422016, field, redactor)
//line object_mashaller.qtpl:46
	qt422016.ReleaseWriter(qw422016)
//line object_mashaller.qtpl:46
}

//line object_mashaller.qtpl:46
func RenderValueRedacted(field domain.RedactedField, redactor string) string {
//line object_mashaller.qtpl:46
	qb422016 := qt422016.AcquireByteBuffer()
//line object_mashaller.qtpl:46
	WriteRenderValueRedacted(qb422016, field, redactor)
//line object_mashaller.qtpl:46
	qs422016 := string(qb422016.B)
//line object_mashaller.qtpl:46
	qt422016.ReleaseByteBuffer(qb422016)
//line object_mashaller.qtpl:46
	return qs422016
//line object_mashaller.qtpl:46
}

//line object_mashaller.qtpl:48
func StreamRenderObjectRedacted(qw422016 *qt422016.Writer, field domain.RedactedField) {
//line object_mashaller.qtpl:48
	qw422016.N().S(`	`)
//line object_mashaller.qtpl:49
	if field.IsPointer {
//line object_mashaller.qtpl:49
		qw422016.N().S(`	if s.`)
//line object_mashaller.qtpl:50
		qw422016.E().S(field.Name)
//line object_mashaller.qtpl:50
		qw422016.N().S(` == nil {
		encoder.AddReflected("`)
//line object_mashaller.qtpl:51
		qw422016.E().S(field.ExportedName)
//line object_mashaller.qtpl:51
		qw422016.N().S(`", nil)
	} else {
`)
//line object_mashaller.qtpl:53
	}
//line object_mashaller.qtpl:53
	qw422016.N().S(`	encoder.AddObject("`)
//line object_mashaller.qtpl:54
	qw422016.E().S(field.ExportedName)
//line object_mashaller.qtpl:54
	qw422016.N().S(`", zapredactor.RedactObject(`)
//line object_mashaller.qtpl:54
	if !field.IsPointer {
//line object_mashaller.qtpl:54
		qw422016.N().S(`&`)
//line object_mashaller.qtpl:54
	}
//line object_mashaller.qtpl:54
	qw422016.N().S(`s.`)
//line object_mashaller.qtpl:54
	qw422016.E().S(field.Name)
//line object_mashaller.qtpl:54
	qw422016.N().S(`))
`)
//line object_mashaller.qtpl:55
	if field.IsPointer {
//line object_mashaller.qtpl:55
		qw422016.N().S(`	}
`)
//line object_mashaller.qtpl:57
	}
//line object_mashaller.qtpl:58
}

//line object_mashaller.qtpl:58
func WriteRenderObjectRedacted(qq422016 qtio422016.Writer, field domain.RedactedField) {
//line object_mashaller.qtpl:58
	qw422016 := qt422016.AcquireWriter(qq422016)
//line object_mashaller.qtpl:58
	StreamRenderObjectRedacted(qw422016, field)
//line object_mashaller.qtpl:58
	qt422016.ReleaseWriter(qw422016)
//line object_mashaller.qtpl:58
}

//line object_mashaller.qtpl:58
func RenderObjectRedacted(field domain.RedactedField) string {
//line object_mashaller.qtpl:58
	qb422016 := qt422016.AcquireByteBuffer()
//line object_mashaller.qtpl:58
	WriteRenderObjectRedacted(qb422016, field)
//line object_mashaller.qtpl:58
	qs422016 := string(qb422016.B)
//line object_mashaller.qtpl:58
	qt422016.ReleaseByteBuffer(qb422016)
//line object_mashaller.qtpl:58
	return qs422016
//line object_mashaller.qtpl:58
}
